### ISSUE TITLE
site-test.js issue!

### ISSUE THREAD

**Issue by rajkumarpb** [dylants/generator-price-finder-site#12]
The generator file looks okay, but when I run yo price-finder-site, instead of should, I am still getting the expect in test case, which mean Mocha is not updated. But in generator file, it is added! Weird. Any idea why it happens?

**Comment by dylants** [comment]
Hmm... that's weird.  Can you verify the version of the `generator-price-finder-site` module?

Try running the following command to see what you have installed:

```
$ npm list -g --depth=0
```

**Comment by rajkumarpb** [comment]
it says 1.0.0!! I've deleted my forked repo, and forked again and then tried. Still it generate the old file? How can it be possible?

**Comment by dylants** [comment]
The fork can be used as the npm binary, but only if you use `npm link`.  To avoid having to do that, you can simply install the generator from npmjs:

```
$ npm install -g generator-price-finder-site
```

Or if you've already installed it, and want to update it to the latest version:

```
$ npm update -g generator-price-finder-site
```

**Comment by rajkumarpb** [comment]
Ok! Will update
